import { rm } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { defineConfig } from 'astro/config';

// Local-only preview assets are generated by the #185 build script into
// public/assets/dev/ so a developer can review them in astro dev. They are
// untracked and must never reach a deployed static build, so the build-done
// hook removes them from dist after Astro has copied public/.
function pruneLocalOnlyAssets() {
  return {
    name: 'prune-local-only-preview-assets',
    hooks: {
      async 'astro:build:done'({ dir }) {
        await rm(fileURLToPath(new URL('assets/dev', dir)), {
          recursive: true,
          force: true,
        });
      },
    },
  };
}

export default defineConfig({
  site: 'https://chabiko.pages.dev',
  output: 'static',
  compressHTML: true,
  integrations: [pruneLocalOnlyAssets()],
  server: {
    host: '0.0.0.0',
    port: 3000,
  },
  // v1 is a static-first site — no backend or SSR needed.
});
